apiVersion: v1
kind: Service
metadata:
  name: cargo-tracker-service
  namespace: cargo-tracker
  labels:
    app: cargo-tracker
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: cargo-tracker
