apiVersion: v1
kind: Service
metadata:
  name: cargo-tracker-service
  namespace: cargo-tracker
  labels:
    app: cargo-tracker
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8081
    protocol: TCP
  - name: jms
    port: 7276
    targetPort: 7276
    protocol: TCP
  - name: jms-ssl
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    app: cargo-tracker
  sessionAffinity: None